version: "3"
services:
  bookworm-app:
    container_name: hubx-app
    image: dockerfile
    restart: always
    build: .
    ports:
      - "9700:9700"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - '27018:27017'